# Generated by Django 5.2.1 on 2025-05-18 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_carddetails_guest_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='guest_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_details', to='store.guestcustomer'),
        ),
    ]
