# Generated by Django 5.2.1 on 2025-06-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_carddetails_guest_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='name',
            field=models.CharField(choices=[('suv', 'SUV'), ('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('pickup_truck', 'Pickup Truck'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('estate', 'Estate'), ('minivan', 'Minivan'), ('crossover', 'Crossover')], max_length=20, unique=True),
        ),
    ]
