# Generated by Django 5.2.1 on 2025-06-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_carddetails_guest_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='expiry_date',
            field=models.CharField(max_length=5),
        ),
    ]
