# Generated by Django 5.2.1 on 2025-07-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('return_requested', 'Return request initiated'), ('return_accepted', 'Return request accepted'), ('return_denied', 'Return request denied')], default='processing', max_length=20),
        ),
    ]
