# Generated by Django 5.2.1 on 2025-07-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_review'),
        ('store', '0017_alter_order_status'),
    ]

    operations = [
    ]
